~V
VERS. 2.0 :CWLS LOG ASCII STANDARD - VERSION 2.0
WRAP. NO :One line per depth step
~W
STRT.FT 2563 :START DEPTH
STOP.FT 15000 :STOP DEPTH
STEP.FT 0.5 :STEP
NULL. -999.25 :NULL VALUE
UWI.  :UNIQUE WELL ID
WELL. XXXXXXXXXXXXXXXXX :WELL
DATE.  :DATE
COMP.  :COMPANY
LOC.  :LOCATION
PROV.  :PROVINCE
SRVC.  :SERVICE COMPANY
FLD.  :FIELD
~C
DEPTH.FT  :DEPTH
TotalGas.  :
C1_MS.  :
C2_MS.  :
C3_MS.  :
C4_MS.  :
C5_MS.  :
C6_MS.  :
C7_MS.  :
C8_MS.  :
C9_MS.  :
C10_MS.  :
C4OBM_MS.  :
C5OBM_MS.  :
C6OBM_MS.  :
C7OBM_MS.  :
C8OBM_MS.  :
C9OBM_MS.  :
Character.  :
Wetness.  :
Balance.  :
Aromatics.  :
Naphthenes.  :
Paraffins.  :
Benzene/Toluene.  :
Benzene/cC6.  :
Benzene/nC6.  :
CO2raw.  :
CO2/C1.  :
CO2calc.  :
Helium.  :
He/C1.  :
Hydrogen.  :
Pixler1/2.  :
Pixler1/3.  :
Pixler1/4.  :
Pixler1/5.  :
ROP.  :
C2/C1.  :
C3/C1.  :
C5/C3.  :
C7/C3.  :
AceticAcid.  :
Benzene.  :
Toluene.  :
H2S.  :
SO.  :
SO2S2.  :
CS2.  :
Nitrogen.  :
Oxygen.  :
Argon.  :
Water.  :
Machine_Temperature.  :
~A
8369 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 0.2 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25 -999.25